 //------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccentureAcademy.Libreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.EscritoPor = new HashSet<EscritoPor>();
            this.Pertenece = new HashSet<Pertenece>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime AnioPublicacion { get; set; }
        public int NroPaginas { get; set; }
        public string ISBN { get; set; }
        public int Id_Editorial { get; set; }
    
        public virtual Editorial Editorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EscritoPor> EscritoPor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pertenece> Pertenece { get; set; }
    }
}
